// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as Vitest$1 from "vitest";

Vitest.testAsync("promise", undefined, (async function (param) {
        var res = await Promise.resolve(42);
        return Vitest$1.expect(res).toEqual(42);
      }));

export {
  
}
/*  Not a pure module */
