// Generated by ReScript, PLEASE EDIT WITH CARE


function reduce(arr, init, f) {
  return arr.reduce(f, init);
}

function reduceWithIndex(arr, init, f) {
  return arr.reduce(f, init);
}

function reduceRight(arr, init, f) {
  return arr.reduceRight(f, init);
}

function reduceRightWithIndex(arr, init, f) {
  return arr.reduceRight(f, init);
}

function head(arr) {
  return arr[0];
}

function isEmpty(arr) {
  var match = arr[0];
  return match === undefined;
}

export {
  reduce ,
  reduceWithIndex ,
  reduceRight ,
  reduceRightWithIndex ,
  head ,
  isEmpty ,
}
/* No side effect */
