// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function catchMap(opt, f) {
  if (opt !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(opt));
  } else {
    return Caml_option.some(Curry._1(f, undefined));
  }
}

function chain(opt, f) {
  if (opt !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(opt));
  }
  
}

function filter(opt, f) {
  if (opt === undefined) {
    return ;
  }
  var x = Caml_option.valFromOption(opt);
  if (Curry._1(f, x)) {
    return Caml_option.some(x);
  }
  
}

function fold(opt, noneFn, someFn) {
  if (opt !== undefined) {
    return Curry._1(someFn, Caml_option.valFromOption(opt));
  } else {
    return Curry._1(noneFn, undefined);
  }
}

function forEach(opt, f) {
  if (opt !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(opt));
  }
  
}

function getOrElse(opt, v) {
  if (opt !== undefined) {
    return Caml_option.valFromOption(opt);
  } else {
    return Curry._1(v, undefined);
  }
}

function isNone(opt) {
  return opt === undefined;
}

function isSome(opt) {
  return opt !== undefined;
}

function map(opt, f) {
  if (opt !== undefined) {
    return Caml_option.some(Curry._1(f, Caml_option.valFromOption(opt)));
  }
  
}

export {
  catchMap ,
  chain ,
  filter ,
  fold ,
  forEach ,
  getOrElse ,
  isNone ,
  isSome ,
  map ,
}
/* No side effect */
