// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function catchMap(opt, f) {
  if (opt !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(opt));
  } else {
    return Caml_option.some(Curry._1(f, undefined));
  }
}

function chain(opt, f) {
  if (opt !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(opt));
  }
  
}

function filter(opt, f) {
  if (opt === undefined) {
    return ;
  }
  var x = Caml_option.valFromOption(opt);
  if (Curry._1(f, x)) {
    return Caml_option.some(x);
  }
  
}

function fold(opt, noneFn, someFn) {
  if (opt !== undefined) {
    return Curry._1(someFn, Caml_option.valFromOption(opt));
  } else {
    return Curry._1(noneFn, undefined);
  }
}

function forEach(opt, f) {
  if (opt !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(opt));
  }
  
}

function getOrElse(opt, v) {
  if (opt !== undefined) {
    return Caml_option.valFromOption(opt);
  } else {
    return Curry._1(v, undefined);
  }
}

function isNone(opt) {
  return opt === undefined;
}

function isSome(opt) {
  return opt !== undefined;
}

function map(opt, f) {
  if (opt !== undefined) {
    return Caml_option.some(Curry._1(f, Caml_option.valFromOption(opt)));
  }
  
}

function map2(opt1, opt2, f) {
  var match = [
    opt1,
    opt2
  ];
  if (match.length !== 2) {
    return ;
  }
  var x1 = match[0];
  if (x1 === undefined) {
    return ;
  }
  var x2 = match[1];
  if (x2 !== undefined) {
    return Caml_option.some(Curry._2(f, Caml_option.valFromOption(x1), Caml_option.valFromOption(x2)));
  }
  
}

function map3(opt1, opt2, opt3, f) {
  var match = [
    opt1,
    opt2,
    opt3
  ];
  if (match.length !== 3) {
    return ;
  }
  var x1 = match[0];
  if (x1 === undefined) {
    return ;
  }
  var x2 = match[1];
  if (x2 === undefined) {
    return ;
  }
  var x3 = match[2];
  if (x3 !== undefined) {
    return Caml_option.some(Curry._3(f, Caml_option.valFromOption(x1), Caml_option.valFromOption(x2), Caml_option.valFromOption(x3)));
  }
  
}

function orElseRun(opt, f) {
  if (opt !== undefined) {
    return ;
  } else {
    return Curry._1(f, undefined);
  }
}

export {
  catchMap ,
  chain ,
  filter ,
  fold ,
  forEach ,
  getOrElse ,
  isNone ,
  isSome ,
  map ,
  map2 ,
  map3 ,
  orElseRun ,
}
/* No side effect */
