module Array = Fp_core__Array
module Option = Fp_core__Option

// passthroughs to RescriptCore
module Promise = RescriptCore.Promise
module Int = RescriptCore.Int
module BigInt = RescriptCore.BigInt
module Console = RescriptCore.Console
module Dict = RescriptCore.Dict
module Error = RescriptCore.Error
module Float = RescriptCore.Float
module Iterator = RescriptCore.Iterator
module JSON = RescriptCore.JSON
module List = RescriptCore.List
module Map = RescriptCore.Map
module Math = RescriptCore.Math
module Ordering = RescriptCore.Ordering
module RegExp = RescriptCore.RegExp
module Set = RescriptCore.Set
module Symbol = RescriptCore.Symbol
module Type = RescriptCore.Type
module WeakMap = RescriptCore.WeakMap
module WeakSet = RescriptCore.WeakSet
module Intl = RescriptCore.Intl
